import { useState } from 'react';
import { ArrowDownToLine, ChevronRight, Upload } from 'lucide-react';
import MetricCard from '../components/MetricCard';
import ProductTable from '../components/ProductTable';

export default function Overview({ dashboard, onNavigate, notify, onReorder, onReview }) {
    
  const [period, setPeriod] = useState('7');
  const riskProducts = dashboard.products.filter((product ) => (product.risk >= 60));
  const metrics = [
    { label: 'Inventory health', value: dashboard.metrics.health, unit: '%', change: '↑ 4.2%', tone: 'teal' },
    { label: 'At stockout risk', value: dashboard.metrics.stockoutRisk, unit: ' SKUs', change: '↑ 2', tone: 'coral' },
    { label: 'Overstocked', value: dashboard.metrics.overstocked, unit: ' SKUs', change: '↓ 6', tone: 'amber' },
    { label: 'Forecast accuracy', value: dashboard.metrics.accuracy, unit: '% WAPE', change: '↑ 1.8%', tone: 'blue' }
  ];
  return( <section className="view active-view">
   
    <div className="page-heading"><div><p className="eyebrow">Tuesday, September 8, 2026</p><h1>Good morning, Jordan <span className="heading-wave">✦</span></h1><p className="lede">Here’s what needs your attention across <strong>24,482 SKUs</strong>.</p></div><div className="heading-actions"><button className="button secondary" onClick={() => onNavigate('data')}><Upload size={14} /> Upload data</button><button className="button primary" onClick={() => notify('Under Progress...')}><ArrowDownToLine size={14} /> Export report</button></div></div>
    <div className="metric-grid">{metrics.map((metric, index) => <MetricCard key={metric.label} {...metric} index={index} />)}</div>
    <div className="dashboard-grid">
      <article className="panel forecast-panel"><div className="panel-header"><div><p className="eyebrow">Demand outlook</p><h2>Forecast vs actual</h2></div><div className="segmented">{['7', '14', '30'].map(value => <button key={value} className={`period ${period === value ? 'active' : ''}`} onClick={() => { setPeriod(value); notify(`Showing the ${value}-day demand outlook.`); }}>{value} days</button>)}</div></div><div className="chart-legend"><span><i className="legend-dot actual" /> Actual demand</span><span><i className="legend-line" /> Forecast</span><span className="confidence-key">90% confidence</span></div><div className="line-chart"><div className="y-labels"><span>1.2k</span><span>900</span><span>600</span><span>300</span><span>0</span></div><div className="plot"><div className="grid-line g1" /><div className="grid-line g2" /><div className="grid-line g3" /><div className="grid-line g4" /><div className="grid-line g5" /><svg viewBox="0 0 720 270" preserveAspectRatio="none"><path className="confidence-area" d="M0,160 C80,130 100,155 160,120 S250,105 300,138 S390,95 445,112 S520,75 580,92 S660,62 720,74 L720,140 C660,122 620,154 580,120 S510,140 445,145 S370,140 300,165 S220,145 160,150 S70,185 0,198Z" /><path className="actual-line" d="M0,195 C58,175 85,135 145,158 S230,183 290,145 S365,150 420,120" /><path className="forecast-line" d="M420,120 C475,108 510,128 560,97 S630,74 720,86" /></svg><div className="x-labels"><span>Sep 01</span><span>Sep 04</span><span>Today</span><span>Sep 12</span><span>Sep 15</span></div></div></div><div className="forecast-insight"><span className="insight-spark">✦</span><p><strong>{dashboard.insight.split('.')[0]}.</strong>{dashboard.insight.split('.').slice(1).join('.')}</p><button className="text-button" onClick={() => onNavigate('forecasts')}>View forecast details <ChevronRight size={12} /></button></div></article>
      <article className="panel distribution-panel"><div className="panel-header"><div><p className="eyebrow">Portfolio health</p><h2>Inventory distribution</h2></div></div><div className="donut-wrap"><div className="donut"><div className="donut-hole"><strong>24,482</strong><small>total SKUs</small></div></div><div className="distribution-list"><div><span className="key-dot healthy" /><span>Healthy</span><b>19,690</b><small>80.4%</small></div><div><span className="key-dot watch" /><span>Watch</span><b>4,792</b><small>19.6%</small></div><div><span className="key-dot critical" /><span>Critical</span><b>60</b><small>0.2%</small></div></div></div><div className="distribution-foot"><span className="status-dot" /> Portfolio health is <strong>above target</strong></div></article>
    </div>
    <div className="bottom-grid"><article className="panel risk-panel"><div className="panel-header"><div><p className="eyebrow">Action required</p><h2>Stockout risk</h2></div><button className="text-button" onClick={() => onNavigate('alerts')}>View all 8 <ChevronRight size={12} /></button></div><ProductTable compact products={riskProducts} onReorder={product => notify(`Reorder recommendation added for ${product.name}.`)} /></article><article className="panel movers-panel"><div className="panel-header"><div><p className="eyebrow">Demand signals</p><h2>Top movers</h2></div></div>{dashboard.products.slice(3, 6).map((product, index) => <div className="mover-row" key={product.sku}><div className="mover-rank">0{index + 1}</div><div className="product-thumb bottle">◒</div><div className="mover-info"><strong>{product.name}</strong><small>{product.category}</small></div><span className={`mover-change ${index === 2 ? 'down' : 'up'}`}>{index === 2 ? '-12%' : `+${38 - index * 14}%`}</span></div>)}</article></div>
  </section>);
}
